#!/bin/bash
DOCKERFILE=Dockerfile-rpi
TAG=rpi-latest
TIMESTAMP=`date +"%Y%m%d%H%M%S"`
ARCH=`uname -a | awk '{print $13}'`
if ! [[ "$ARCH" == armv* ]]
then
    echo "Script should be run on an armv architecture"
    exit 1
fi
docker build -f $DOCKERFILE --force-rm=true --rm=true --build-arg TIMESTAMP=$TIMESTAMP -t apendergast/ceg-docker-base:$TAG .
