FROM resin/armhf-alpine:edge
RUN [ "cross-build-start" ]
RUN apk --update add bash git python build-base nodejs nodejs-npm
RUN npm install -ddd --unsafe-perm -g webpack webpack-dev-server node-sass babel-core
RUN [ "cross-build-end" ]
