#!/bin/bash
DOCKERFILE=Dockerfile
TAG=gateway-latest
TIMESTAMP=`date +"%Y%m%d%H%M%S"`
docker build -f $DOCKERFILE --force-rm=true --rm=true --build-arg TIMESTAMP=$TIMESTAMP -t apendergast/ceg-docker-base:$TAG .
