#!/bin/bash
DOCKERFILE=Dockerfile
TAG=ui-latest
TIMESTAMP=`date +"%Y%m%d%H%M%S"`
docker build -f $DOCKERFILE --pull --force-rm=true --rm=true --build-arg TIMESTAMP=$TIMESTAMP -t toneffectory/ceg-docker-base:$TAG .
